Repository ITA-OneByte/OneByte-FE, pull requests merged in 2024-11, with the labels that each got.

#8 feat: layout완성
  src/Router.tsx
  src/assets/font/PyeongChangPeace-Bold.ttf
  src/assets/font/PyeongChangPeace-Light.ttf
  src/assets/header/gray.svg
  src/assets/header/profile.svg
  src/assets/header/white.svg
  src/assets/managesidebar/blueplus.svg
  src/assets/managesidebar/downarrow.svg
  src/assets/managesidebar/kebab.svg
  src/assets/managesidebar/plus.svg
  src/assets/managesidebar/rightarrow.svg
  src/assets/sidebar/board.svg
  src/assets/sidebar/calendar.svg
  src/assets/sidebar/drive.svg
  src/assets/sidebar/manage.svg
  src/assets/sidebar/selectboard.svg
  src/assets/sidebar/selectcalendar.svg
  src/assets/sidebar/selectdrive.svg
  src/assets/sidebar/selectmanage.svg
  src/components/.gitkeep
  src/components/header/Header.styles.tsx
  src/components/header/index.tsx
  src/components/layout/Layout.styles.tsx
  src/components/layout/Layout.types.ts
  src/components/layout/index.tsx
  src/components/layout/managelayout/ManageLayout.types.ts
  src/components/layout/managelayout/index.tsx
  src/components/managesidebar/Attendance.tsx
  src/components/managesidebar/Info.tsx
  src/components/managesidebar/ManageSidebar.styles.tsx
  src/components/managesidebar/index.tsx
  src/components/sidebar/Sidebar.styles.tsx
  src/components/sidebar/index.tsx
  src/pages/home/index.tsx
  src/styles/GlobalStyles.tsx
Labels: ✨ Feature

#12 feat: sms페이지 완성 및 path 완성
  src/Router.tsx
  src/components/layout/Layout.styles.tsx
  src/components/managesidebar/Attendance.tsx
  src/components/managesidebar/ManageSidebar.styles.tsx
  src/components/path/Path.styles.tsx
  src/components/path/index.tsx
  src/components/sidebar/Sidebar.styles.tsx
  src/pages/home/index.tsx
  src/pages/sms/Sms.styles.tsx
  src/pages/sms/index.tsx
Labels: ✨ Feature

#14 feat: 학생 목록 UI 추가
  src/Router.tsx
  src/assets/info/checkBox.svg
  src/assets/info/search.svg
  src/assets/info/selectedCheckBox.svg
  src/components/button/Button.styles.tsx
  src/components/button/Button.types.ts
  src/components/button/index.tsx
  src/pages/studentInfo/index.tsx
  src/pages/studentInfo/studentList/StudentList.styles.tsx
  src/pages/studentInfo/studentList/index.tsx
  src/pages/studentInfo/studentRegister/StudentRegister.styles.tsx
  src/pages/studentInfo/studentRegister/index.tsx
Labels: ✨ Feature

#17 feat: 경로 추가 및 학생 등록 페이지 UI 완성
  src/assets/info/arrowBottom.svg
  src/components/dropDown/DropDown.styles.tsx
  src/components/dropDown/DropDown.types.ts
  src/components/dropDown/index.tsx
  src/pages/studentInfo/StudentInfo.styles.tsx
  src/pages/studentInfo/studentList/StudentList.styles.tsx
  src/pages/studentInfo/studentList/index.tsx
  src/pages/studentInfo/studentRegister/StudentRegister.styles.tsx
  src/pages/studentInfo/studentRegister/index.tsx
Labels: ✨ Feature

#19 fix: 삭제 모달 메세지 수정
  src/components/modal/questionModal/QuestionModal.styles.tsx
  src/components/modal/questionModal/QuestionModal.types.ts
  src/components/modal/questionModal/index.tsx
Labels: 🔥 Fix

#20 Feat#18
  index.html
  src/components/label/Label.styles.tsx
  src/components/managesidebar/Attendance.tsx
  src/components/managesidebar/ManageSidebar.styles.tsx
  src/components/modal/Modal.types.ts
  src/components/modal/index.tsx
  src/components/modal/questionModal/QuestionModal.types.ts
  src/components/modal/questionModal/index.tsx
  src/components/popup/Popup.styles.tsx
  src/pages/.gitkeep
  src/pages/sms/index.tsx
  src/styles/.gitkeep
Labels: ✨ Feature

#25 api기본 세팅
  package-lock.json
  package.json
  src/api/.gitkeep
  src/api/attendanceAPI.ts
  src/api/instance.ts
  src/api/subclassAPI.ts
  src/components/managesidebar/Attendance.tsx
  src/constants/.gitkeep
  src/constants/API.ts
  src/types/subclass.type.ts
Labels: 📬 API

#27 Feat#22: 학생 등록 페이지 API 연결 완료
  .gitignore
  src/api/classAPI.ts
  src/api/studentAPI.ts
  src/components/dropDown/DropDown.styles.tsx
  src/components/dropDown/DropDown.types.ts
  src/components/dropDown/classDropDown/ClassDropDown.styles.tsx
  src/components/dropDown/classDropDown/ClassDropDown.types.ts
  src/components/dropDown/classDropDown/index.tsx
  src/components/dropDown/index.tsx
  src/constants/API.ts
  src/constants/STUDENT.ts
  src/hooks/.gitkeep
  src/hooks/useStudentRegister.ts
  src/pages/studentInfo/studentRegister/index.tsx
  src/types/.gitkeep
  src/types/class.type.ts
  src/types/student.type.ts
Labels: 📬 API

#29 Feat#23: 학생 목록 페이지 API 연결 완료
  src/api/studentAPI.ts
  src/components/modal/studentInfoModal/StudentInfoModal.types.ts
  src/components/modal/studentInfoModal/index.tsx
  src/hooks/useStudentList.ts
  src/pages/studentInfo/StudentInfo.styles.tsx
  src/pages/studentInfo/studentList/StudentList.styles.tsx
  src/pages/studentInfo/studentList/index.tsx
  src/types/student.type.ts
Labels: 📬 API

#30 사이드바 sms api연결
  .gitignore
  src/api/classAPI.ts
  src/api/mainclassAPI.ts
  src/api/smsAPI.ts
  src/api/studentAPI.ts
  src/components/label/Label.styles.tsx
  src/components/managesidebar/Attendance.tsx
  src/components/managesidebar/Attendance.type.ts
  src/components/managesidebar/ManageSidebar.styles.tsx
  src/constants/API.ts
  src/hooks/useGetClassInfo.ts
  src/pages/attendance/Attendance.styles.tsx
  src/pages/attendance/index.tsx
  src/pages/sms/index.tsx
  src/types/mainclass.type.ts
  src/types/sms.type.ts
Labels: 📬 API

#33 feat: 전체학생 출결 조회 api 연결
  src/Router.tsx
  src/api/attendanceAPI.ts
  src/assets/attendanceTable/default.svg
  src/components/attendanceTable/AttendanceTable.types.ts
  src/components/attendanceTable/index.tsx
  src/components/managesidebar/Attendance.tsx
  src/components/modal/studentInfoModal/StudentInfoModal.types.ts
  src/components/modal/studentInfoModal/index.tsx
  src/constants/API.ts
  src/pages/attendance/Attendance.styles.tsx
  src/pages/attendance/index.tsx
  src/pages/studentInfo/studentList/index.tsx
  src/store/.gitkeep
  src/store/classStore.ts
  src/types/attendance.type.ts
  vite.config.d.ts
  vite.config.js
Labels: 📬 API

#35 feat: deploy오류 해결용 vercel.json 추가
  vercel.json
  vite.config.js
  vite.config.ts
Labels: 🌏 Deploy

#37 fix: 학생 정보 모달 초기화 로직 수정
  src/components/modal/studentInfoModal/index.tsx
  src/hooks/student/useStudentList.ts
  src/pages/studentInfo/studentList/StudentList.styles.tsx
  src/pages/studentInfo/studentList/index.tsx
Labels: 🔥 Fix

#39 feat: sms api 연결 및 subclass 중복 오류
  src/components/managesidebar/Attendance.tsx
  src/pages/attendance/index.tsx
  src/pages/sms/index.tsx
Labels: 📬 API

#42 Feat#40
  src/api/attendanceAPI.ts
  src/api/excelAPI.ts
  src/components/attendanceTable/AttendanceTable.styles.tsx
  src/components/attendanceTable/AttendanceTable.types.ts
  src/components/attendanceTable/index.tsx
  src/components/managesidebar/ManageSidebar.styles.tsx
  src/components/path/index.tsx
  src/pages/attendance/Attendance.type.ts
  src/pages/attendance/index.tsx
  src/pages/studentInfo/studentList/StudentList.styles.tsx
  src/types/attendance.type.ts
  src/types/excel.type.ts
  src/utils/formatDate.ts
  src/utils/formatExcelData.ts
Labels: 📬 API

#46 Deployv2
  vercel.json
Labels: 🌏 Deploy

#47 deploy용 커밋
  vercel.json
Labels: 🌏 Deploy

#48 deploy 오류 수정
  vercel.json
Labels: 🌏 Deploy

#54 local https 설정
  .gitignore
  package-lock.json
  package.json
  vite.config.ts
Labels: ⚙ Chore

#55 Feat#50: 학생성적 관리 목록 페이지 UI 완성
  src/Router.tsx
  src/components/managesidebar/index.tsx
  src/constants/STUDENT.ts
  src/pages/achievement/Achievement.styles.tsx
  src/pages/achievement/Achievement.types.ts
  src/pages/achievement/achievementList/AchievementList.styles.tsx
  src/pages/achievement/achievementList/index.tsx
  src/pages/achievement/index.tsx
  src/types/achievement.type.ts
Labels: ✨ Feature

#59 Feat#52: 성적 상세 페이지 UI 완성
  src/Router.tsx
  src/components/button/Button.styles.tsx
  src/pages/achievement/Achievement.styles.tsx
  src/pages/achievement/achievementDetail/AchievementDetail.styles.tsx
  src/pages/achievement/achievementDetail/index.tsx
  src/pages/achievement/achievementInfoEdit/AchievementInfoEdit.styles.tsx
  src/pages/achievement/achievementInfoEdit/index.tsx
  src/pages/achievement/achievementList/AchievementList.styles.tsx
  src/pages/achievement/achievementList/index.tsx
  src/pages/achievement/achievementScoreEdit/AchievementScoreEdit.styles.tsx
  src/pages/achievement/achievementScoreEdit/index.tsx
  src/pages/achievement/index.tsx
Labels: ✨ Feature

#60 Feat#51: 성적관리 등록 페이지 UI 완성
  src/assets/buttonIcon/toggle.svg
  src/assets/buttonIcon/toggleFilled.svg
  src/components/dropDown/DropDown.types.ts
  src/components/dropDown/index.tsx
  src/pages/achievement/Achievement.styles.tsx
  src/pages/achievement/achievementList/index.tsx
  src/pages/achievement/achievementRegister/AchievementRegister.styles.tsx
  src/pages/achievement/achievementRegister/index.tsx
  src/pages/achievement/achievementRegisterStudent/AchievementRegisterStudent.styles.tsx
  src/pages/achievement/achievementRegisterStudent/index.tsx
  src/pages/achievement/index.tsx
Labels: ✨ Feature
